In [20]:
'''
根据以下博客编写，第一次上手keras，MNIST就算是hello world啦~
http://nooverfit.com/wp/keras-手把手入门1-手写数字识别-深度学习实战/#more-2354
'''

from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense,Dropout,Flatten
from keras.layers import Conv2D,MaxPooling2D
from keras import backend as K
import numpy as np

In [21]:
batch_size=128
num_classes=10
epochs=12

img_rows,img_cols=28,28
#(x_train,y_train),(x_test,y_test)=mnist.load_data()
path='mnist.npz'
f = np.load(path)  
x_train, y_train = f['x_train'], f['y_train']  
x_test, y_test = f['x_test'], f['y_test'] 
print(x_train)

if K.image_data_format()=='channels_first':
    x_train=x_train.reshape(x_train.shape[0],1,img_rows,img_cols)
    x_test=x_test.reshape(x_test.shape[0],1,img_rows,img_cols)
    input_shape=(1,img_rows,img_cols)
else:
    x_train=x_train.reshape(x_train.shape[0],img_rows,img_cols,1)
    x_test=x_test.reshape(x_test.shape[0],img_rows,img_cols,1)
    input_shape=(img_rows,img_cols,1)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [22]:
#把数据变成float32更精确
x_train=x_train.astype('float32')
x_test=x_test.astype('float32')
x_train/=255
x_test/=255
print('x_train shape:',x_train.shape)
print(x_train.shape[0],'train sampeles')
print(x_test.shape[0],'test samples')

import keras
#把类别0-9变成二进制，方便训练
y_train=keras.utils.np_utils.to_categorical(y_train,num_classes)
y_test=keras.utils.np_utils.to_categorical(y_test,num_classes)

x_train shape: (60000, 28, 28, 1)
60000 train sampeles
10000 test samples


In [25]:
#构造训练CNN
model=Sequential()
model.add(Conv2D(32,
                 activation='relu',
                 input_shape=input_shape,
                 nb_row=3,
                 nb_col=3))
model.add(Conv2D(64,activation='relu',nb_row=3,nb_col=3))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.35))
model.add(Flatten())
model.add(Dense(128,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes,activation='softmax'))

model.compile(loss=keras.metrics.categorical_crossentropy,
             optimizer=keras.optimizers.Adadelta(),
             metrics=['accuracy'])

model.fit(x_train,
          y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test,y_test))

score=model.evaluate(x_test,y_test,verbose=0)
print('Test loss:',score[0])
print('Test accuracy:',score[1])

C:\Users\dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), activation="relu", input_shape=(28, 28, 1...)`
  import sys
C:\Users\dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), activation="relu")`
  


Train on 60000 samples, validate on 10000 samples
Epoch 1/12
60000/60000 [==============================] - 196s 3ms/step - loss: 0.2754 - acc: 0.9145 - val_loss: 0.0659 - val_acc: 0.9798
Epoch 2/12
60000/60000 [==============================] - 181s 3ms/step - loss: 0.0908 - acc: 0.9726 - val_loss: 0.0414 - val_acc: 0.9862
Epoch 3/12
60000/60000 [==============================] - 181s 3ms/step - loss: 0.0695 - acc: 0.9794 - val_loss: 0.0354 - val_acc: 0.9878
Epoch 4/12
60000/60000 [==============================] - 181s 3ms/step - loss: 0.0574 - acc: 0.9824 - val_loss: 0.0329 - val_acc: 0.9885
Epoch 5/12
60000/60000 [==============================] - 182s 3ms/step - loss: 0.0506 - acc: 0.9852 - val_loss: 0.0353 - val_acc: 0.9878
Epoch 6/12
60000/60000 [==============================] - 181s 3ms/step - loss: 0.0440 - acc: 0.9864 - val_loss: 0.0309 - val_acc: 0.9901
Epoch 7/12
60000/60000 [==============================] - 186s 3ms/step - loss: 0.0411 - acc: 0.9875 - val_loss: 0.0331 - 